/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.3/userguide/multi_project_builds.html
 */

rootProject.name = "lae-i41d"
include("aula04-reflect")
include("aula05-reflect-instance-and-func-call")
include("aula06-logger")
include("aula06-sample-domain")